# Generated by Django 4.2.7 on 2025-09-01 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_bugs_found', models.IntegerField(default=0)),
                ('total_points_awarded', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard Stats',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('bugs_found', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-total_score', '-bugs_found', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_identifier', models.CharField(max_length=200)),
                ('points_awarded', models.IntegerField()),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_discoveries', to='leaderboard_app.leaderboarduser')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'unique_together': {('user', 'bug_identifier')},
            },
        ),
    ]
